name: play_hq
description: Play hq flutter front end

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  provider: ^6.0.5
  rxdart: ^0.27.7
  get_it: 7.2.0
  event_bus: 2.0.0
  dartz: 0.10.1
  api_cache_manager: ^1.0.2
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.18.5+1

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  firebase_messaging: ^14.2.1

  # Utils
  flutter_launcher_icons: ^0.11.0
  flutter_secure_storage: ^7.0.1
  path_provider: ^2.0.12
  hive: ^2.2.3
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  http_extensions_cache: ^1.0.0
  http_extensions: ^1.0.0
  http_extensions_log: ^1.0.0

  # Google Maps
  places_service: ^0.1.2
  google_maps_flutter: ^2.2.3
  geolocator: ^8.2.1
  geocoding: ^2.0.5

  # UI
  cupertino_icons: ^1.0.5
  lottie: ^2.2.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  sticky_headers: ^0.3.0+2
  flutter_typeahead: ^4.1.1
  dotted_border: ^2.0.0+3
  rect_getter: ^1.1.0
  flutter_svg: ^1.1.6
  skeleton_text: 3.0.0
  dots_indicator: ^2.1.0
  another_flushbar: ^1.12.29
  flutter_sticky_header: ^0.6.4
  badges: ^3.0.2
  rflutter_alert: 2.0.4
  skeletons: ^0.0.3
  
  # Network
  http: ^0.13.5

  # SSO (Single sign-on)
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^5.0.7
  
flutter_icons:
  image_path: 'assets/images/logo@3x.png'
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular Std Book
      fonts:
        - asset: assets/fonts/CircularBook.ttf

    - family: Neusa Std
      fonts:
        - asset: assets/fonts/NeusaNextStd.ttf

    - family: Neusa Std Bold
      fonts:
        - asset: assets/fonts/NeusaNextStd-Bold.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
